# Generated by Django 2.2 on 2021-05-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zooName', models.CharField(max_length=45)),
                ('zooLocation', models.CharField(max_length=255)),
                ('zooCreateAt', models.DateTimeField(auto_now_add=True)),
                ('zooUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=45)),
                ('shopDescription', models.CharField(max_length=255)),
                ('shopZoo', models.ManyToManyField(related_name='zooShop', to='officalZooApp.Zoo')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='officalZooApp.Zoo')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalName', models.CharField(max_length=45)),
                ('animalType', models.CharField(max_length=45)),
                ('animalBirth', models.DateField()),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='officalZooApp.Zoo')),
            ],
        ),
    ]
