# Generated by Django 2.2 on 2021-05-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officalZooApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showName', models.CharField(max_length=45)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='officalZooApp.Zoo')),
            ],
        ),
    ]
